-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.7
-- Sat Apr  2 17:23:07 2022

-- parameterized module component declaration
component pll1
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic; 
        CLKOS3: out  std_logic; LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll1
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__, CLKOS3=>__, 
        LOCK=>__);
