#ifndef HTTP_CODES_H_
#define HTTP_CODES_H_

#define HTTP_OK 200
#define HTTP_BAD_REQUEST 400
#define HTTP_FORBIDDEN 403
#define HTTP_NOT_FOUND 404
#define HTTP_METHOD_NOT_ALLOWED 405
#define HTTP_PRECONDITION_FAILED 412
#define HTTP_UNSUPPORTED_MEDIA_TYPE 415
#define HTTP_LOCKED 423
#define HTTP_FAILED_DEPENDENCY 424
#define HTTP_INTERNAL_SERVER_ERROR 500
#define HTTP_NOT_IMPLEMENTED 501
#define HTTP_SERVICE_UNAVAILABLE 503
#define HTTP_INSUFFICIENT_STORAGE 507

#endif
