<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>fileTypes</key>
		<array>
			<string>asm</string>
			<string>ASM</string>
		</array>
		<key>name</key>
		<string>64tass</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>;.*$</string>
				<key>name</key>
				<string>comment.line</string>
			</dict>
			<dict>
				<key>match</key>
				<string>"[^"]*"|'[^']*'</string>
				<key>name</key>
				<string>string.quoted</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b((([0-9]+\.?[0-9]*)|(\.[0-9]+))([eEpP](\+|-)?[0-9]+)?)\b</string>
				<key>name</key>
				<string>constant.numeric</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\$(([0-9a-fA-F]_+)+[0-9a-fA-F]|[0-9a-fA-F])+\b</string>
				<key>name</key>
				<string>constant.numeric</string>
			</dict>
			<dict>
				<key>match</key>
				<string>%(([01]_+)+[01]|[01])+\b</string>
				<key>name</key>
				<string>constant.numeric</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^[0-9a-zA-Z_]+\b|^[+-]</string>
				<key>name</key>
				<string>entity.name.function</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(^|\s)\.(byte|binary|char|ptext|lint|long|null|dword|sint|fill|rta|shift|shiftl|dint|word|text|dstruct|dunion|dsection|addr)\b</string>
				<key>name</key>
				<string>storage.type</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(^|\s)\.(al|align|as|assert|bend|binclude|block|cdef|cerror|check|cpu|cwarn|databank|dpage|edef|enc|end|endp|eor|error|for|goto|here|hidemac|include|lbl|logical|next|offs|option|page|proff|pron|rept|showmac|var|warn|xl|xs|proc|if|ifeq|ifne|ifpl|ifmi|else|elsif|switch|default|case|segment|macro|section|function|struct|union|pend|fi|endif|endswitch|endm|send|endf|ends|endu|comment|endc|break|continue|weak|endweak|autsiz|mansiz|seed)\b</string>
				<key>name</key>
				<string>keyword.control</string>
			</dict>
			<dict>
				<key>match</key>
				<string>[-+*/%&lt;&gt;=`!#^&amp;|\\,()\[\]{}]|\bin\b|\bx\b</string>
				<key>name</key>
				<string>keyword.operator</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)\b(adc|and|asl|bcc|bcs|beq|bge|bit|blt|bmi|bne|bpl|brk|bvc|bvs|clc|cld|cli|clv|cmp|cpx|cpy|dec|dex|dey|eor|gcc|gcs|geq|gge|glt|gmi|gne|gpl|gvc|gvs|inc|inx|iny|jmp|jsr|lda|ldx|ldy|lsr|nop|ora|pha|php|pla|plp|rol|ror|rti|rts|sbc|sec|sed|sei|shl|shr|sta|stx|sty|tax|tay|tsx|txa|txs|tya)\b(?-i)</string>
				<key>name</key>
				<string>keyword</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(?i)\b(ahx|alr|anc|ane|arr|asr|axs|dcm|dcp|ins|isb|isc|jam|lae|las|lax|lds|lxa|rla|rra|sax|sbx|sha|shs|shx|shy|slo|sre|tas|xaa)\b(?-i)</string>
				<key>name</key>
				<string>keyword.other</string>
			</dict>
		</array>
		<key>scopeName</key>
		<string>source.64tass</string>
	</dict>
</plist>
