#ifndef USB_HID_CONFIG_H
#define USB_HID_CONFIG_H

#define CFG_WHEEL_MODE        0x55
#define CFG_SCROLL_FACTOR     0x56
#define CFG_WHEEL_DIRECTION   0x57
#define CFG_MENU_MOUSE_NAV    0x58
#define CFG_USB_MOUSE_NAME    0x59
#define CFG_USB_MOUSE_MODE    0x5A
#define CFG_USB_KEYBOARD_NAME 0x5B
#define CFG_USB_KEYBOARD_MODE 0x5C
#define CFG_MOUSE_SENSITIVITY 0x5D
#define CFG_MOUSE_ACCELERATION 0x5E

#endif
