// update_remote_update_0.v

// This file was auto-generated from altera_remote_update_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 15.1 185

`timescale 1 ps / 1 ps
module update_remote_update_0 (
		output wire        busy,        //        busy.busy
		output wire [28:0] data_out,    //    data_out.data_out
		input  wire [2:0]  param,       //       param.param
		input  wire        read_param,  //  read_param.read_param
		input  wire        reconfig,    //    reconfig.reconfig
		input  wire        reset_timer, // reset_timer.reset_timer
		input  wire [1:0]  read_source, // read_source.read_source
		input  wire        clock,       //       clock.clk
		input  wire        reset        //       reset.reset
	);

	altera_remote_update_core remote_update_core (
		.read_param  (read_param),  //  read_param.read_param
		.param       (param),       //       param.param
		.reconfig    (reconfig),    //    reconfig.reconfig
		.reset_timer (reset_timer), // reset_timer.reset_timer
		.clock       (clock),       //       clock.clk
		.reset       (reset),       //       reset.reset
		.busy        (busy),        //        busy.busy
		.data_out    (data_out),    //    data_out.data_out
		.read_source (read_source), // read_source.read_source
		.ctl_nupdt   (1'b0)         // (terminated)
	);

endmodule
