# TCL File Generated by Component Editor 15.1
# Sat Apr 23 11:39:47 CEST 2016
# DO NOT MODIFY


# 
# mem32_to_avalon "Memory bus to Avalon Master Bridge" v1.0
#  2016.04.23.11:39:47
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module mem32_to_avalon
# 
set_module_property DESCRIPTION ""
set_module_property NAME mem32_to_avalon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Bridges and Adaptors"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Memory bus to Avalon Master Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mem32_to_avalon_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mem32_to_avalon_bridge.vhd VHDL PATH ../ip/busses/vhdl_source/mem32_to_avalon_bridge.vhd TOP_LEVEL_FILE

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL mem32_to_avalon_bridge
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file mem32_to_avalon_bridge.vhd VHDL PATH ../ip/busses/vhdl_source/mem32_to_avalon_bridge.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point mem32_slave
# 
add_interface mem32_slave conduit end
set_interface_property mem32_slave associatedClock clock
set_interface_property mem32_slave associatedReset reset
set_interface_property mem32_slave ENABLED true
set_interface_property mem32_slave EXPORT_OF ""
set_interface_property mem32_slave PORT_NAME_MAP ""
set_interface_property mem32_slave CMSIS_SVD_VARIABLES ""
set_interface_property mem32_slave SVD_ADDRESS_GROUP ""

add_interface_port mem32_slave memreq_address address Input 26
add_interface_port mem32_slave memreq_read_writen direction Input 1
add_interface_port mem32_slave memreq_byte_en byte_en Input 4
add_interface_port mem32_slave memreq_data wdata Input 32
add_interface_port mem32_slave memreq_request request Input 1
add_interface_port mem32_slave memreq_tag tag Input 8
add_interface_port mem32_slave memresp_dack_tag dack_tag Output 8
add_interface_port mem32_slave memresp_data rdata Output 32
add_interface_port mem32_slave memresp_rack rack Output 1
add_interface_port mem32_slave memresp_rack_tag rack_tag Output 8


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 2
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avm_read read Output 1
add_interface_port avalon_master avm_write write Output 1
add_interface_port avalon_master avm_address address Output 26
add_interface_port avalon_master avm_writedata writedata Output 32
add_interface_port avalon_master avm_byte_enable byteenable Output 4
add_interface_port avalon_master avm_ready waitrequest_n Input 1
add_interface_port avalon_master avm_readdata readdata Input 32
add_interface_port avalon_master avm_readdatavalid readdatavalid Input 1

