-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.12.0.240.2
-- Module  Version: 5.7
-- Mon Aug 15 22:57:28 2022

-- parameterized module component declaration
component pll2
    port (CLKI: in  std_logic; CLKFB: in  std_logic; 
        CLKOP: out  std_logic; CLKOS: out  std_logic; 
        LOCK: out  std_logic);
end component;

-- parameterized module component instance
__ : pll2
    port map (CLKI=>__, CLKFB=>__, CLKOP=>__, CLKOS=>__, LOCK=>__);
