# TCL File Generated by Component Editor 15.1
# Thu Nov 03 16:26:39 CET 2016
# DO NOT MODIFY


# 
# usb_host "NanoUSB" v1.0
# Gideon Zweijtzer 2016.11.03.16:26:39
# Simple USB Host controller
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module usb_host
# 
set_module_property DESCRIPTION "Simple USB Host controller"
set_module_property NAME usb_host
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols"
set_module_property AUTHOR "Gideon Zweijtzer"
set_module_property DISPLAY_NAME NanoUSB
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_usb
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_usb.vhd VHDL PATH ../io/usb2/altera/avalon_usb.vhd
add_fileset_file async_fifo_ft.vhd VHDL PATH ../altera/async_fifo_ft.vhd
add_fileset_file srl_fifo.vhd VHDL PATH ../altera/srl_fifo.vhd
add_fileset_file usb_cmd_nano.vhd VHDL PATH ../io/usb2/vhdl_source/usb_cmd_nano.vhd
add_fileset_file pulse_synchronizer.vhd VHDL PATH ../ip/synchroniser/vhdl_source/pulse_synchronizer.vhd
add_fileset_file level_synchronizer.vhd VHDL PATH ../ip/synchroniser/vhdl_source/level_synchronizer.vhd
add_fileset_file align_read_to_bram.vhd VHDL PATH ../altera/align_read_to_bram.vhd
add_fileset_file mem_remain_counter.vhd VHDL PATH ../io/usb2/vhdl_source/mem_remain_counter.vhd
add_fileset_file mem_addr_counter.vhd VHDL PATH ../io/usb2/vhdl_source/mem_addr_counter.vhd
add_fileset_file usb_memory_ctrl.vhd VHDL PATH ../io/usb2/vhdl_source/usb_memory_ctrl.vhd
add_fileset_file timer.vhd VHDL PATH ../io/usb2/vhdl_source/timer.vhd
add_fileset_file host_sequencer.vhd VHDL PATH ../io/usb2/vhdl_source/host_sequencer.vhd
add_fileset_file usb_host_interface.vhd VHDL PATH ../io/usb2/vhdl_source/usb_host_interface.vhd
add_fileset_file io_bus_splitter.vhd VHDL PATH ../ip/busses/vhdl_source/io_bus_splitter.vhd
add_fileset_file distributed_stack.vhd VHDL PATH ../altera/distributed_stack.vhd
add_fileset_file unisim_VPKG.vhd VHDL PATH ../altera/xilinx_primitives/unisim_VPKG.vhd
add_fileset_file unisim_VCOMP.vhd VHDL PATH ../altera/xilinx_primitives/unisim_VCOMP.vhd
add_fileset_file RAMB16BWE_S36_S9.vhd VHDL PATH ../altera/xilinx_primitives/RAMB16BWE_S36_S9.vhd
add_fileset_file RAMB16_S9_S36.vhd VHDL PATH ../altera/xilinx_primitives/RAMB16_S9_S36.vhd
add_fileset_file RAMB16_S9_S18.vhd VHDL PATH ../altera/xilinx_primitives/RAMB16_S9_S18.vhd
add_fileset_file usb_pkg.vhd VHDL PATH ../io/usb2/vhdl_source/usb_pkg.vhd
add_fileset_file usb_cmd_pkg.vhd VHDL PATH ../io/usb2/vhdl_source/usb_cmd_pkg.vhd
add_fileset_file endianness_pkg.vhd VHDL PATH ../ip/busses/vhdl_source/endianness_pkg.vhd
add_fileset_file mem_bus_pkg.vhd VHDL PATH ../ip/busses/vhdl_source/mem_bus_pkg.vhd
add_fileset_file io_bus_pkg.vhd VHDL PATH ../ip/busses/vhdl_source/io_bus_pkg.vhd
add_fileset_file avalon_to_io_bridge.vhd VHDL PATH ../ip/busses/vhdl_source/avalon_to_io_bridge.vhd
add_fileset_file nano_cpu_pkg.vhd VHDL PATH ../ip/nano_cpu/vhdl_source/nano_cpu_pkg.vhd
add_fileset_file nano_cpu.vhd VHDL PATH ../ip/nano_cpu/vhdl_source/nano_cpu.vhd
add_fileset_file nano_alu.vhd VHDL PATH ../ip/nano_cpu/vhdl_source/nano_alu.vhd
add_fileset_file nano.vhd VHDL PATH ../ip/nano_cpu/vhdl_source/nano.vhd
add_fileset_file usb_host_nano.vhd VHDL PATH ../io/usb2/vhdl_source/usb_host_nano.vhd
add_fileset_file ulpi_tx.vhd VHDL PATH ../io/usb2/vhdl_source/ulpi_tx.vhd
add_fileset_file ulpi_rx.vhd VHDL PATH ../io/usb2/vhdl_source/ulpi_rx.vhd
add_fileset_file ulpi_pkg.vhd VHDL PATH ../io/usb2/vhdl_source/ulpi_pkg.vhd
add_fileset_file ulpi_bus.vhd VHDL PATH ../io/usb2/vhdl_source/ulpi_bus.vhd
add_fileset_file token_crc_check.vhd VHDL PATH ../io/usb2/vhdl_source/token_crc_check.vhd
add_fileset_file token_crc_19.vhd VHDL PATH ../io/usb2/vhdl_source/token_crc_19.vhd
add_fileset_file token_crc.vhd VHDL PATH ../io/usb2/vhdl_source/token_crc.vhd
add_fileset_file rxtx_to_buf.vhd VHDL PATH ../io/usb2/vhdl_source/rxtx_to_buf.vhd
add_fileset_file nano_minimal_io.vhd VHDL PATH ../io/usb2/vhdl_source/nano_minimal_io.vhd
add_fileset_file data_crc.vhd VHDL PATH ../io/usb2/vhdl_source/data_crc.vhd
add_fileset_file bridge_to_mem_ctrl.vhd VHDL PATH ../io/usb2/vhdl_source/bridge_to_mem_ctrl.vhd

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL avalon_usb
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_usb.vhd VHDL PATH ../io/usb2/altera/avalon_usb.vhd
add_fileset_file async_fifo_ft.vhd VHDL PATH ../altera/async_fifo_ft.vhd
add_fileset_file srl_fifo.vhd VHDL PATH ../altera/srl_fifo.vhd
add_fileset_file usb_cmd_nano.vhd VHDL PATH ../io/usb2/vhdl_source/usb_cmd_nano.vhd
add_fileset_file pulse_synchronizer.vhd VHDL PATH ../ip/synchroniser/vhdl_source/pulse_synchronizer.vhd
add_fileset_file level_synchronizer.vhd VHDL PATH ../ip/synchroniser/vhdl_source/level_synchronizer.vhd
add_fileset_file align_read_to_bram.vhd VHDL PATH ../altera/align_read_to_bram.vhd
add_fileset_file mem_remain_counter.vhd VHDL PATH ../io/usb2/vhdl_source/mem_remain_counter.vhd
add_fileset_file mem_addr_counter.vhd VHDL PATH ../io/usb2/vhdl_source/mem_addr_counter.vhd
add_fileset_file usb_memory_ctrl.vhd VHDL PATH ../io/usb2/vhdl_source/usb_memory_ctrl.vhd
add_fileset_file timer.vhd VHDL PATH ../io/usb2/vhdl_source/timer.vhd
add_fileset_file host_sequencer.vhd VHDL PATH ../io/usb2/vhdl_source/host_sequencer.vhd
add_fileset_file usb_host_interface.vhd VHDL PATH ../io/usb2/vhdl_source/usb_host_interface.vhd
add_fileset_file io_bus_splitter.vhd VHDL PATH ../ip/busses/vhdl_source/io_bus_splitter.vhd
add_fileset_file distributed_stack.vhd VHDL PATH ../altera/distributed_stack.vhd
add_fileset_file unisim_VPKG.vhd VHDL PATH ../altera/xilinx_primitives/unisim_VPKG.vhd
add_fileset_file unisim_VCOMP.vhd VHDL PATH ../altera/xilinx_primitives/unisim_VCOMP.vhd
add_fileset_file RAMB16BWE_S36_S9.vhd VHDL PATH ../altera/xilinx_primitives/RAMB16BWE_S36_S9.vhd
add_fileset_file RAMB16_S9_S36.vhd VHDL PATH ../altera/xilinx_primitives/RAMB16_S9_S36.vhd
add_fileset_file RAMB16_S9_S18.vhd VHDL PATH ../altera/xilinx_primitives/RAMB16_S9_S18.vhd
add_fileset_file usb_pkg.vhd VHDL PATH ../io/usb2/vhdl_source/usb_pkg.vhd
add_fileset_file usb_cmd_pkg.vhd VHDL PATH ../io/usb2/vhdl_source/usb_cmd_pkg.vhd
add_fileset_file endianness_pkg.vhd VHDL PATH ../ip/busses/vhdl_source/endianness_pkg.vhd
add_fileset_file mem_bus_pkg.vhd VHDL PATH ../ip/busses/vhdl_source/mem_bus_pkg.vhd
add_fileset_file io_bus_pkg.vhd VHDL PATH ../ip/busses/vhdl_source/io_bus_pkg.vhd
add_fileset_file avalon_to_io_bridge.vhd VHDL PATH ../ip/busses/vhdl_source/avalon_to_io_bridge.vhd
add_fileset_file nano_cpu_pkg.vhd VHDL PATH ../ip/nano_cpu/vhdl_source/nano_cpu_pkg.vhd
add_fileset_file nano_cpu.vhd VHDL PATH ../ip/nano_cpu/vhdl_source/nano_cpu.vhd
add_fileset_file nano_alu.vhd VHDL PATH ../ip/nano_cpu/vhdl_source/nano_alu.vhd
add_fileset_file nano.vhd VHDL PATH ../ip/nano_cpu/vhdl_source/nano.vhd
add_fileset_file usb_host_nano.vhd VHDL PATH ../io/usb2/vhdl_source/usb_host_nano.vhd
add_fileset_file ulpi_tx.vhd VHDL PATH ../io/usb2/vhdl_source/ulpi_tx.vhd
add_fileset_file ulpi_rx.vhd VHDL PATH ../io/usb2/vhdl_source/ulpi_rx.vhd
add_fileset_file ulpi_pkg.vhd VHDL PATH ../io/usb2/vhdl_source/ulpi_pkg.vhd
add_fileset_file ulpi_bus.vhd VHDL PATH ../io/usb2/vhdl_source/ulpi_bus.vhd
add_fileset_file token_crc_check.vhd VHDL PATH ../io/usb2/vhdl_source/token_crc_check.vhd
add_fileset_file token_crc_19.vhd VHDL PATH ../io/usb2/vhdl_source/token_crc_19.vhd
add_fileset_file token_crc.vhd VHDL PATH ../io/usb2/vhdl_source/token_crc.vhd
add_fileset_file rxtx_to_buf.vhd VHDL PATH ../io/usb2/vhdl_source/rxtx_to_buf.vhd
add_fileset_file nano_minimal_io.vhd VHDL PATH ../io/usb2/vhdl_source/nano_minimal_io.vhd
add_fileset_file data_crc.vhd VHDL PATH ../io/usb2/vhdl_source/data_crc.vhd
add_fileset_file bridge_to_mem_ctrl.vhd VHDL PATH ../io/usb2/vhdl_source/bridge_to_mem_ctrl.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits SYMBOLS
set_interface_property avalon_slave_0 associatedClock sys_clock
set_interface_property avalon_slave_0 associatedReset sys_reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 1
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_address address Input 13
add_interface_port avalon_slave_0 avs_writedata writedata Input 8
add_interface_port avalon_slave_0 avs_ready waitrequest_n Output 1
add_interface_port avalon_slave_0 avs_readdata readdata Output 8
add_interface_port avalon_slave_0 avs_readdatavalid readdatavalid Output 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint avalon_slave_0
set_interface_property irq bridgedReceiverOffset ""
set_interface_property irq bridgesToReceiver ""
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq CMSIS_SVD_VARIABLES ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq avs_irq irq Output 1


# 
# connection point avalon_master_0
# 
add_interface avalon_master_0 avalon start
set_interface_property avalon_master_0 addressUnits SYMBOLS
set_interface_property avalon_master_0 associatedClock sys_clock
set_interface_property avalon_master_0 associatedReset sys_reset
set_interface_property avalon_master_0 bitsPerSymbol 8
set_interface_property avalon_master_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_0 burstcountUnits WORDS
set_interface_property avalon_master_0 doStreamReads false
set_interface_property avalon_master_0 doStreamWrites false
set_interface_property avalon_master_0 holdTime 0
set_interface_property avalon_master_0 linewrapBursts false
set_interface_property avalon_master_0 maximumPendingReadTransactions 0
set_interface_property avalon_master_0 maximumPendingWriteTransactions 0
set_interface_property avalon_master_0 readLatency 0
set_interface_property avalon_master_0 readWaitTime 1
set_interface_property avalon_master_0 setupTime 0
set_interface_property avalon_master_0 timingUnits Cycles
set_interface_property avalon_master_0 writeWaitTime 0
set_interface_property avalon_master_0 ENABLED true
set_interface_property avalon_master_0 EXPORT_OF ""
set_interface_property avalon_master_0 PORT_NAME_MAP ""
set_interface_property avalon_master_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_0 avm_read read Output 1
add_interface_port avalon_master_0 avm_write write Output 1
add_interface_port avalon_master_0 avm_address address Output 26
add_interface_port avalon_master_0 avm_writedata writedata Output 32
add_interface_port avalon_master_0 avm_byteenable byteenable Output 4
add_interface_port avalon_master_0 avm_ready waitrequest_n Input 1
add_interface_port avalon_master_0 avm_readdata readdata Input 32
add_interface_port avalon_master_0 avm_readdatavalid readdatavalid Input 1


# 
# connection point ulpi
# 
add_interface ulpi conduit end
set_interface_property ulpi associatedClock ""
set_interface_property ulpi associatedReset ""
set_interface_property ulpi ENABLED true
set_interface_property ulpi EXPORT_OF ""
set_interface_property ulpi PORT_NAME_MAP ""
set_interface_property ulpi CMSIS_SVD_VARIABLES ""
set_interface_property ulpi SVD_ADDRESS_GROUP ""

add_interface_port ulpi ulpi_data ulpi_data Bidir 8
add_interface_port ulpi ulpi_dir ulpi_dir Input 1
add_interface_port ulpi ulpi_nxt ulpi_nxt Input 1
add_interface_port ulpi ulpi_stp ulpi_stp Output 1


# 
# connection point sys_clock
# 
add_interface sys_clock clock end
set_interface_property sys_clock clockRate 0
set_interface_property sys_clock ENABLED true
set_interface_property sys_clock EXPORT_OF ""
set_interface_property sys_clock PORT_NAME_MAP ""
set_interface_property sys_clock CMSIS_SVD_VARIABLES ""
set_interface_property sys_clock SVD_ADDRESS_GROUP ""

add_interface_port sys_clock sys_clock clk Input 1


# 
# connection point ulpi_clock
# 
add_interface ulpi_clock clock end
set_interface_property ulpi_clock clockRate 0
set_interface_property ulpi_clock ENABLED true
set_interface_property ulpi_clock EXPORT_OF ""
set_interface_property ulpi_clock PORT_NAME_MAP ""
set_interface_property ulpi_clock CMSIS_SVD_VARIABLES ""
set_interface_property ulpi_clock SVD_ADDRESS_GROUP ""

add_interface_port ulpi_clock ulpi_clock clk Input 1


# 
# connection point sys_reset
# 
add_interface sys_reset reset end
set_interface_property sys_reset associatedClock sys_clock
set_interface_property sys_reset synchronousEdges DEASSERT
set_interface_property sys_reset ENABLED true
set_interface_property sys_reset EXPORT_OF ""
set_interface_property sys_reset PORT_NAME_MAP ""
set_interface_property sys_reset CMSIS_SVD_VARIABLES ""
set_interface_property sys_reset SVD_ADDRESS_GROUP ""

add_interface_port sys_reset sys_reset reset Input 1


# 
# connection point ulpi_reset
# 
add_interface ulpi_reset reset end
set_interface_property ulpi_reset associatedClock ulpi_clock
set_interface_property ulpi_reset synchronousEdges DEASSERT
set_interface_property ulpi_reset ENABLED true
set_interface_property ulpi_reset EXPORT_OF ""
set_interface_property ulpi_reset PORT_NAME_MAP ""
set_interface_property ulpi_reset CMSIS_SVD_VARIABLES ""
set_interface_property ulpi_reset SVD_ADDRESS_GROUP ""

add_interface_port ulpi_reset ulpi_reset reset Input 1

