
library ECP5U;
use ECP5U.components.all;

architecture lattice of dpram_8x16 is
    signal delayed_reset_a  : std_logic;
    signal delayed_reset_b  : std_logic;
begin
    delayed_reset_a <= SSRA when falling_edge(CLKA);
    delayed_reset_b <= SSRB when falling_edge(CLKB);

    true_dpram_8x16: DP16KD
        generic map (
            INIT_DATA     =>  "STATIC",
            ASYNC_RESET_RELEASE =>  "SYNC",
            CSDECODE_B    => "0b000",
            CSDECODE_A    => "0b000",
            WRITEMODE_B   => "NORMAL",
            WRITEMODE_A   => "NORMAL",
            GSR           => "ENABLED",
            RESETMODE     => "ASYNC",
            REGMODE_B     => "NOREG",
            REGMODE_A     => "NOREG",
            DATA_WIDTH_B  => 18,
            DATA_WIDTH_A  => 9)
        port map (
            DIA17 => '0',
            DIA16 => '0',
            DIA15 => '0',
            DIA14 => '0',
            DIA13 => '0',
            DIA12 => '0',
            DIA11 => '0',
            DIA10 => '0',
            DIA9  => '0',
            DIA8  => '0',
            DIA7  => DIA(7),
            DIA6  => DIA(6),
            DIA5  => DIA(5),
            DIA4  => DIA(4),
            DIA3  => DIA(3),
            DIA2  => DIA(2),
            DIA1  => DIA(1),
            DIA0  => DIA(0),
            ADA13 => ADDRA(10),
            ADA12 => ADDRA(9),
            ADA11 => ADDRA(8),
            ADA10 => ADDRA(7),
            ADA9  => ADDRA(6),
            ADA8  => ADDRA(5),
            ADA7  => ADDRA(4),
            ADA6  => ADDRA(3),
            ADA5  => ADDRA(2),
            ADA4  => ADDRA(1),
            ADA3  => ADDRA(0),
            ADA2  => '0',
            ADA1  => '0',
            ADA0  => '0',
            CEA   => ENA,
            OCEA  => ENA,
            CLKA  => CLKA,
            WEA   => WEA,
            CSA2  => '0',
            CSA1  => '0',
            CSA0  => '0',
            RSTA  => delayed_reset_a,
            DIB17 => '0',
            DIB16 => DIB(15),
            DIB15 => DIB(14),
            DIB14 => DIB(13),
            DIB13 => DIB(12),
            DIB12 => DIB(11),
            DIB11 => DIB(10),
            DIB10 => DIB(9),
            DIB9  => DIB(8),
            DIB8  => '0',
            DIB7  => DIB(7),
            DIB6  => DIB(6),
            DIB5  => DIB(5),
            DIB4  => DIB(4),
            DIB3  => DIB(3),
            DIB2  => DIB(2),
            DIB1  => DIB(1),
            DIB0  => DIB(0),
            ADB13 => ADDRB(9),
            ADB12 => ADDRB(8),
            ADB11 => ADDRB(7),
            ADB10 => ADDRB(6),
            ADB9  => ADDRB(5),
            ADB8  => ADDRB(4),
            ADB7  => ADDRB(3),
            ADB6  => ADDRB(2),
            ADB5  => ADDRB(1),
            ADB4  => ADDRB(0),
            ADB3  => '0',
            ADB2  => '0',
            ADB1  => '1',
            ADB0  => '1',
            CEB   => ENB,
            OCEB  => ENB,
            CLKB  => CLKB,
            WEB   => WEB,
            CSB2  => '0',
            CSB1  => '0',
            CSB0  => '0',
            RSTB  => delayed_reset_b,
            DOA17 => open,
            DOA16 => open,
            DOA15 => open,
            DOA14 => open,
            DOA13 => open,
            DOA12 => open,
            DOA11 => open,
            DOA10 => open,
            DOA9  => open,
            DOA8  => open,
            DOA7  => DOA(7),
            DOA6  => DOA(6),
            DOA5  => DOA(5),
            DOA4  => DOA(4),
            DOA3  => DOA(3),
            DOA2  => DOA(2),
            DOA1  => DOA(1),
            DOA0  => DOA(0),
            DOB17 => open,
            DOB16 => DOB(15),
            DOB15 => DOB(14),
            DOB14 => DOB(13),
            DOB13 => DOB(12),
            DOB12 => DOB(11),
            DOB11 => DOB(10),
            DOB10 => DOB(9),
            DOB9  => DOB(8),
            DOB8  => open,
            DOB7  => DOB(7),            
            DOB6  => DOB(6),
            DOB5  => DOB(5),
            DOB4  => DOB(4),
            DOB3  => DOB(3),
            DOB2  => DOB(2),
            DOB1  => DOB(1),
            DOB0  => DOB(0));

end architecture;
