#!/usr/bin/env python3
"""Writes the OpenAPI documents for the REST API from the firmware sources.

    generate.py generate    write doc/api/rest_api_openapi_{u2,u64}.yaml
    generate.py check       rebuild in memory and fail if the committed files differ
    generate.py paths       print the path of each document, one per line

Every REST call is registered through the API_CALL macro in software/api/routes.h,
which already carries the verb, the route, the command and the query parameters.
Which of those registrations a product serves follows from the route sources its
makefiles compile and the macros they are compiled with. The prose that a route
cannot know is written in an API_DOC block above it, which expands to nothing and
so never reaches the firmware image.

Both halves are cross checked before anything is written, so a call without a
block, a block without a call, a parameter only one of them knows about, or a path
template that no longer matches its route, all fail the build. So does anything
declared twice, and so does a family whose targets do not all serve the same calls.

`make openapi_validate` additionally checks the written documents against the
OpenAPI 3.1 specification with openapi-spec-validator, which needs the host
package in tools/openapi/requirements.txt and so is its own target.
"""

import argparse
import os
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

import document
import schemas
import yaml_writer
from errors import OpenApiError

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
OUTPUT_DIR = "doc/api"
OUTPUT_NAME = "rest_api_openapi_%s.yaml"

_HEADER = """\
# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.yaml
# Generated by tools/openapi/generate.py from the firmware route sources. Do not edit.
# Run `make openapi` after changing an API_CALL or its API_DOC block.
"""


def output_path(profile, repo_root=REPO_ROOT):
    return pathlib.Path(repo_root) / OUTPUT_DIR / (OUTPUT_NAME % profile)


def render(built):
    return _HEADER + yaml_writer.dump(built)


def _rendered(repo_root):
    return {profile: render(built) for profile, built in document.build_all(repo_root).items()}


def generate(repo_root=REPO_ROOT):
    written = []
    for profile, text in _rendered(repo_root).items():
        target = output_path(profile, repo_root)
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text)
        written.append(target)
    return written


def stale(repo_root=REPO_ROOT):
    out = []
    for profile, text in _rendered(repo_root).items():
        target = output_path(profile, repo_root)
        relative = os.path.relpath(target, repo_root)
        if not target.exists():
            out.append("%s is missing" % relative)
        elif target.read_text() != text:
            out.append("%s is out of date" % relative)
    return out


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("command", choices=("generate", "check", "paths"))
    parser.add_argument("--repo-root", default=str(REPO_ROOT))
    arguments = parser.parse_args(argv)
    repo_root = pathlib.Path(arguments.repo_root)

    if arguments.command == "paths":
        for profile in sorted(schemas.PROFILES):
            print(os.path.relpath(output_path(profile, repo_root), repo_root))
        return 0

    try:
        if arguments.command == "generate":
            for target in generate(repo_root):
                print("openapi: wrote %s" % os.path.relpath(target, repo_root))
            return 0
        outdated = stale(repo_root)
    except OpenApiError as error:
        print("openapi: %s" % error, file=sys.stderr)
        return 1

    if outdated:
        print("openapi: the committed specification no longer matches the sources:", file=sys.stderr)
        for line in outdated:
            print("  %s" % line, file=sys.stderr)
        print("Run `make openapi` and commit the result.", file=sys.stderr)
        return 1
    print("openapi: %d documents match the sources" % len(schemas.PROFILES))
    return 0


if __name__ == "__main__":
    sys.exit(main())
