typedef struct {
    const char *timezone;
    const char *utc;
    const char *location;
    const char *posix;
} timezone_entry_t;

const timezone_entry_t zones[] = {
    { "AoE",   "UTC -12",   "US Baker Island", "AOE12" },
    { "NUT",   "UTC -11",   "American Samoa",  "NUT11" },
    { "HST",   "UTC -10",   "Hawaii", "HST10" },
    { "MART",  "UTC -9:30", "French Polynesia", "MART9:30" },
    { "AKST",  "UTC -9",    "Alaska", "AKST9AKDT,M3.2.0/2:00:00,M11.1.0/2:00:00" },
    { "PDT",   "UTC -8",    "Los Angeles", "PST8PDT,M3.2.0/2:00:00,M11.1.0/2:00:00" },
    { "MST",   "UTC -7",    "Denver, Colorado", "MST7MDT,M3.2.0/2:00:00,M11.1.0/2:00:00" },
    { "MST",   "UTC -7",    "Phoenix, Arizona", "MST7" },
    { "CST",   "UTC -6",    "Chicago, Illinois", "CST6CDT,M3.2.0/2:00:00,M11.1.0/2:00:00" },
    { "EST",   "UTC -5",    "New York", "EST5EDT,M3.2.0/2:00:00,M11.1.0/2:00:00" },
    { "ART",   "UTC -3",    "Argentina", "ART3" },
    { "NDT",   "UTC -2:30", "Newfoundland", "NST3:30NDT,M3.2.0/2:00:00,M11.1.0/2:00:00" },
    { "WGST",  "UTC -2",    "Greenland", "WGT3WGST,M3.5.0/0,M10.5.0/1" },
    { "CVT",   "UTC -1",    "Cabo Verde", "CVT1" },
    { "GMT",   "UTC 0",     "Iceland", "GMT0" },
    { "BST",   "UTC +1",    "UK", "GMT0BST,M3.5.0/1,M10.5.0/2" },
    { "CEST",  "UTC +2",    "Western Europe", "CET-1CEST,M3.5.0/2,M10.5.0/3" },
    { "EET",   "UTC +2",    "Greece", "EET-2EEST,M3.5.0/3,M10.5.0/4" },
    { "GST",   "UTC +4",    "Azerbaijan", "AZT-4" },
    { "IRDT",  "UTC +3:30", "Iran", "IRST-3:30" },
    { "UZT",   "UTC +5",    "Pakistan", "PKT-5" },
    { "IST",   "UTC +5:30", "India", "IST-5:30" },
    { "NPT",   "UTC +5:45", "Nepal", "NPT-5:45" },
    { "BST",   "UTC +6",    "Bangladesh", "BST-6" },
    { "MMT",   "UTC +6:30", "Myanmar", "MMT-6:30" },
    { "WIB",   "UTC +7",    "Indonesia", "WIB-7" },
    { "CST",   "UTC +8",    "China", "CST-8" },
    { "AWST",  "UTC +8",    "Western Australia", "AWST-8" },
    { "JST",   "UTC +9",    "Japan", "JST-9" },
    { "ACST",  "UTC +9:30", "Central Australia", "ACST-9:30ACDT,M10.1.0/2,M4.1.0/3" },
    { "AEST",  "UTC +10",   "Eastern Australia", "AEST-10AEDT,M10.1.0/2,M4.1.0/3" },
    { "LHST",  "UTC +10:30","Lord Howe Island", "LHST-10:30LHDT,M10.1.0/2,M4.1.0/2" },
    { "SBT",   "UTC +11",   "Solomon Islands", "SBT-11" },
    { "ANAT",  "UTC +12",   "New Zealand", "NZST-12NZDT,M9.5.0/2,M4.1.0/3" },
    { "CHAST", "UTC +12:45","Chatham Islands", "CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45" },
    { "TOT",   "UTC +13",   "Tonga", "TOT-13" },
    { "LINT",  "UTC +14",   "Christmas Island", "LINT-14" },

    { "AST",   "UTC -4",    "Atlantic Time", "AST4ADT,M3.2.0/2,M11.1.0/2" },
    { "ACST-NT", "UTC +9:30", "Northern Territory", "ACST-9:30" },
    { "AEST-QLD","UTC +10", "Queensland", "AEST-10" },
    { "ACST",  "UTC +9:30", "South Australia", "ACST-9:30ACDT,M10.1.0/2,M4.1.0/3" },
    { "ACWST", "UTC +8:45", "Australia/Eucla", "ACWST-8:45" },
    { "VET",   "UTC -4",    "Venezuela", "VET4" },
    { "CLT",   "UTC -4",    "Chile", "CLT4CLST,M9.1.0/0,M4.1.0/0" },
    { "PET",   "UTC -5",    "Peru", "PET5" },
    { "WAT",   "UTC +1",    "West Africa", "WAT-1" },
    { "SAST",  "UTC +2",    "South Africa", "SAST-2" },
    { "IST",   "UTC +2",    "Israel", "IST-2IDT,M3.4.4/2,M10.5.0/2" },
    { "TRT",   "UTC +3",    "Turkey", "TRT-3" },
};

const char *zone_names[] = {
    "US Baker Island",
    "American Samoa",
    "Hawaii",
    "French Polynesia",
    "Alaska",
    "Los Angeles",
    "Denver, Colorado",
    "Phoenix, Arizona",
    "Chicago, Illinois",
    "New York",
    "Argentina",
    "Newfoundland",
    "Greenland",
    "Cabo Verde",
    "Iceland",
    "UK",
    "Western Europe",
    "Greece",
    "Azerbaijan",
    "Iran",
    "Pakistan",
    "India",
    "Nepal",
    "Bangladesh",
    "Myanmar",
    "Indonesia",
    "China",
    "Western Australia",
    "Japan",
    "Central Australia",
    "Eastern Australia",
    "Lord Howe Island",
    "Solomon Islands",
    "New Zealand",
    "Chatham Islands",
    "Tonga",
    "Christmas Island",
    "Atlantic Time",
    "Northern Australia",
    "Australia/Queensland",
    "South Australia",
    "Australia/Eucla",
    "Venezuela",
    "Chile",
    "Peru",
    "West Africa",
    "South Africa",
    "Israel",
    "Turkey",
};
