typedef struct {
    const char *timezone;
    const char *utc;
    const char *location;
    const char *posix;
} timezone_entry_t;

// The index is the stored setting, so new zones are appended, never inserted.
// Rules follow IANA tzdb 2026e, written in the POSIX TZ subset newlib parses:
// alphabetic names only and no negative times.
const timezone_entry_t zones[] = {
    { "AoE",   "UTC -12",   "US Baker Island", "AOE12" },
    { "SST",   "UTC -11",   "America Samoa",   "SST11" },
    { "HST",   "UTC -10",   "Hawaii", "HST10" },
    { "TAHT",  "UTC -10",   "French Polynesia", "TAHT10" },
    { "AKST",  "UTC -9",    "Alaska", "AKST9AKDT,M3.2.0,M11.1.0" },
    { "PST",   "UTC -8",    "Los Angeles", "PST8PDT,M3.2.0,M11.1.0" },
    { "MST",   "UTC -7",    "Denver, Colorado", "MST7MDT,M3.2.0,M11.1.0" },
    { "MST",   "UTC -7",    "Phoenix, Arizona", "MST7" },
    { "CST",   "UTC -6",    "Chicago, Illinois", "CST6CDT,M3.2.0,M11.1.0" },
    { "EST",   "UTC -5",    "New York", "EST5EDT,M3.2.0,M11.1.0" },
    { "ART",   "UTC -3",    "Argentina", "ART3" },
    { "NST",   "UTC -3:30", "Newfoundland", "NST3:30NDT,M3.2.0,M11.1.0" },
    // tzdb springs forward at 01:00 UTC with M3.5.0/-1; newlib cannot parse a
    // negative time, so the change comes an hour late.
    { "WGT",   "UTC -2",    "Greenland", "WGT2WGST,M3.5.0/0,M10.5.0/0" },
    { "CVT",   "UTC -1",    "Cabo Verde", "CVT1" },
    { "GMT",   "UTC 0",     "Iceland", "GMT0" },
    { "GMT",   "UTC 0",     "UK", "GMT0BST,M3.5.0/1,M10.5.0" },
    { "CET",   "UTC +1",    "Western Europe", "CET-1CEST,M3.5.0,M10.5.0/3" },
    { "EET",   "UTC +2",    "Greece", "EET-2EEST,M3.5.0/3,M10.5.0/4" },
    { "AZT",   "UTC +4",    "Azerbaijan", "AZT-4" },
    { "IRST",  "UTC +3:30", "Iran", "IRST-3:30" },
    { "PKT",   "UTC +5",    "Pakistan", "PKT-5" },
    { "IST",   "UTC +5:30", "India", "IST-5:30" },
    { "NPT",   "UTC +5:45", "Nepal", "NPT-5:45" },
    { "BST",   "UTC +6",    "Bangladesh", "BST-6" },
    { "MMT",   "UTC +6:30", "Myanmar", "MMT-6:30" },
    { "WIB",   "UTC +7",    "Indonesia", "WIB-7" },
    { "CST",   "UTC +8",    "China", "CST-8" },
    { "AWST",  "UTC +8",    "Western Australia", "AWST-8" },
    { "JST",   "UTC +9",    "Japan", "JST-9" },
    { "ACST",  "UTC +9:30", "Central Australia", "ACST-9:30ACDT,M10.1.0,M4.1.0/3" },
    { "AEST",  "UTC +10",   "Eastern Australia", "AEST-10AEDT,M10.1.0,M4.1.0/3" },
    { "LHST",  "UTC +10:30","Lord Howe Island", "LHST-10:30LHDT-11,M10.1.0,M4.1.0" },
    { "SBT",   "UTC +11",   "Solomon Islands", "SBT-11" },
    { "NZST",  "UTC +12",   "New Zealand", "NZST-12NZDT,M9.5.0,M4.1.0/3" },
    { "CHAST", "UTC +12:45","Chatham Islands", "CHAST-12:45CHADT,M9.5.0/2:45,M4.1.0/3:45" },
    { "TOT",   "UTC +13",   "Tonga", "TOT-13" },
    { "LINT",  "UTC +14",   "Christmas Island", "LINT-14" },
    { "HST",   "UTC -10",   "Aleutian Islands", "HST10HDT,M3.2.0,M11.1.0" },
    { "MART",  "UTC -9:30", "Marquesas Islands", "MART9:30" },
    { "GAMT",  "UTC -9",    "Gambier Islands", "GAMT9" },
    { "PNT",   "UTC -8",    "Pitcairn Islands", "PNT8" },
    { "CST",   "UTC -6",    "Mexico, C. America", "CST6" },
    { "EAST",  "UTC -6",    "Easter Island", "EAST6EASST,M9.1.6/22,M4.1.6/22" },
    { "COT",   "UTC -5",    "Colombia, Peru", "COT5" },
    { "CST",   "UTC -5",    "Cuba", "CST5CDT,M3.2.0/0,M11.1.0/1" },
    { "AST",   "UTC -4",    "Venezuela, Caribbean", "AST4" },
    { "AST",   "UTC -4",    "Atlantic Canada", "AST4ADT,M3.2.0,M11.1.0" },
    { "CLT",   "UTC -4",    "Chile", "CLT4CLST,M9.1.6/24,M4.1.6/24" },
    { "PMST",  "UTC -3",    "St Pierre, Miquelon", "PMST3PMDT,M3.2.0,M11.1.0" },
    { "FNT",   "UTC -2",    "Fernando de Noronha", "FNT2" },
    { "AZOT",  "UTC -1",    "Azores", "AZOT1AZOST,M3.5.0/0,M10.5.0/1" },
    { "WAT",   "UTC +1",    "West Africa", "WAT-1" },
    { "SAST",  "UTC +2",    "South Africa", "SAST-2" },
    { "EET",   "UTC +2",    "Egypt", "EET-2EEST,M4.5.5/0,M10.5.4/24" },
    { "IST",   "UTC +2",    "Israel", "IST-2IDT,M3.4.4/26,M10.5.0" },
    { "EET",   "UTC +2",    "Lebanon", "EET-2EEST,M3.5.0/0,M10.5.0/0" },
    { "EET",   "UTC +2",    "Palestine", "EET-2EEST,M3.4.4/50,M10.4.4/50" },
    { "MSK",   "UTC +3",    "Moscow, Istanbul", "MSK-3" },
    { "AFT",   "UTC +4:30", "Afghanistan", "AFT-4:30" },
    { "ACWST", "UTC +8:45", "Eucla, Australia", "ACWST-8:45" },
    { "ACST",  "UTC +9:30", "Northern Territory", "ACST-9:30" },
    { "AEST",  "UTC +10",   "Queensland", "AEST-10" },
    { "NFT",   "UTC +11",   "Norfolk Island", "NFT-11NFDT,M10.1.0,M4.1.0/3" },
    { "FJT",   "UTC +12",   "Fiji", "FJT-12" },
};

const char *zone_names[] = {
    "US Baker Island",
    "America Samoa",
    "Hawaii",
    "French Polynesia",
    "Alaska",
    "Los Angeles",
    "Denver, Colorado",
    "Phoenix, Arizona",
    "Chicago, Illinois",
    "New York",
    "Argentina",
    "Newfoundland",
    "Greenland",
    "Cabo Verde",
    "Iceland",
    "UK",
    "Western Europe",
    "Greece",
    "Azerbaijan",
    "Iran",
    "Pakistan",
    "India",
    "Nepal",
    "Bangladesh",
    "Myanmar",
    "Indonesia",
    "China",
    "Western Australia",
    "Japan",
    "Central Australia",
    "Eastern Australia",
    "Lord Howe Island",
    "Solomon Islands",
    "New Zealand",
    "Chatham Islands",
    "Tonga",
    "Christmas Island",
    "Aleutian Islands",
    "Marquesas Islands",
    "Gambier Islands",
    "Pitcairn Islands",
    "Mexico, C. America",
    "Easter Island",
    "Colombia, Peru",
    "Cuba",
    "Venezuela, Caribbean",
    "Atlantic Canada",
    "Chile",
    "St Pierre, Miquelon",
    "Fernando de Noronha",
    "Azores",
    "West Africa",
    "South Africa",
    "Egypt",
    "Israel",
    "Lebanon",
    "Palestine",
    "Moscow, Istanbul",
    "Afghanistan",
    "Eucla, Australia",
    "Northern Territory",
    "Queensland",
    "Norfolk Island",
    "Fiji",
};
