name: Build_with_docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gideonz/riscv:latest
      options: --user 1001:1001

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate Version String
        run: echo "GIT_VERSION=$(git describe --tags --always)" >>$GITHUB_ENV

      - name: Determine ESP32 dependencies
        shell: bash
        run: |
          make esp_depends

      - name: Cache ESP32 Target
        id: cache-esp32
        uses: actions/cache@v4
        with:
            path: |
                software/u64ctrl/build/u64ctrl.bin
                software/u64ctrl/build/bootloader/bootloader.bin
                software/u64ctrl/build/partition_table/partition-table.bin
            key: ${{ runner.os }}-esp32-${{ hashFiles('software/esp_depends.txt') }}
            restore-keys: |
                ${{ runner.os }}-esp32-${{ hashFiles('software/esp_depends.txt') }}

      - if: steps.cache-esp32.outputs.cache-hit != 'true'
        name: Build ESP32 Software (skipped if available in cache)
        shell: bash
        run: |
            source "$IDF_PATH/export.sh"
            make esp32

      - name: Run Make Target
        shell: bash
        run: |
            source "$IDF_PATH/export.sh"
            make u64ii && mv update.ue2 update_${{ env.GIT_VERSION }}.ue2

      - name: Upload User Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: update_package_${{ env.GIT_VERSION }}
          path: |
            update_${{ env.GIT_VERSION }}.ue2


      - name: Upload Factory Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: factory_package_U64e2_${{ env.GIT_VERSION }}
          path: |
            u64ii/bootloader.bin
            u64ii/partition-table.bin
            u64ii/u64ctrl.bin

            u64ii/ultimate.app
            u64ii/factorytest.bin
